artifacts:
  FACERECOG_MODEL: deepface
  HAARCASCADE_PATH: "data\\models\\haarcascade_frontalface_default.xml"
  INTERMIDEIATE_DIR: "data\\02_intermediate_data"
  CONTOUR_FILE: "contour_id.jpg"
  FACE_IMG1: "data\\02_intermediate_data\\extracted_face.jpg"
  FACE_IMG2: "data\\02_intermediate_data\\face_image.jpg"


secrets:
  HOST: 'localhost'
  USER: 'root'
  PASSWORD: 'toor'
  DB: 'ekyc'